---
abstract: 'Build your distributions like I do'
author:
  - 'Nigel Metheringham <nigelm@cpan.org>'
build_requires:
  Carp: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.3601'
  Scalar::Util: '0'
  Test::More: '0.94'
  perl: '5.006'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-PluginBundle-NIGELM
provides:
  Dist::Zilla::PluginBundle::NIGELM:
    file: lib/Dist/Zilla/PluginBundle/NIGELM.pm
    version: '0.18'
requires:
  Dist::Zilla::Plugin::Authority: '1.005'
  Dist::Zilla::Plugin::AutoPrereqs: '0'
  Dist::Zilla::Plugin::CheckChangeLog: '0'
  Dist::Zilla::Plugin::CopyReadmeFromBuild: '0'
  Dist::Zilla::Plugin::EOLTests: '0'
  Dist::Zilla::Plugin::ExecDir: '0'
  Dist::Zilla::Plugin::ExtraTests: '0'
  Dist::Zilla::Plugin::FakeRelease: '0'
  Dist::Zilla::Plugin::GatherDir: '0'
  Dist::Zilla::Plugin::Git::Check: '0'
  Dist::Zilla::Plugin::Git::Commit: '0'
  Dist::Zilla::Plugin::Git::CommitBuild: '1.110480'
  Dist::Zilla::Plugin::Git::NextVersion: '0'
  Dist::Zilla::Plugin::Git::Push: '0'
  Dist::Zilla::Plugin::Git::Tag: '0'
  Dist::Zilla::Plugin::HasVersionTests: '0'
  Dist::Zilla::Plugin::InlineFiles: '0'
  Dist::Zilla::Plugin::InstallGuide: '0'
  Dist::Zilla::Plugin::KwaliteeTests: '0'
  Dist::Zilla::Plugin::License: '0'
  Dist::Zilla::Plugin::Manifest: '0'
  Dist::Zilla::Plugin::ManifestSkip: '0'
  Dist::Zilla::Plugin::MetaConfig: '0'
  Dist::Zilla::Plugin::MetaJSON: '0'
  Dist::Zilla::Plugin::MetaProvides::Class: '0'
  Dist::Zilla::Plugin::MetaProvides::Package: '0'
  Dist::Zilla::Plugin::MetaResources: '0'
  Dist::Zilla::Plugin::MetaTests: '0'
  Dist::Zilla::Plugin::MetaYAML: '0'
  Dist::Zilla::Plugin::ModuleBuild: '0'
  Dist::Zilla::Plugin::NextRelease: '0'
  Dist::Zilla::Plugin::NoTabsTests: '0'
  Dist::Zilla::Plugin::OurPkgVersion: '0'
  Dist::Zilla::Plugin::PodCoverageTests: '0'
  Dist::Zilla::Plugin::PodSyntaxTests: '0'
  Dist::Zilla::Plugin::PodWeaver: '0'
  Dist::Zilla::Plugin::PruneCruft: '0'
  Dist::Zilla::Plugin::PruneFiles: '0'
  Dist::Zilla::Plugin::ReadmeAnyFromPod: '0'
  Dist::Zilla::Plugin::ReportVersions: '0'
  Dist::Zilla::Plugin::ShareDir: '0'
  Dist::Zilla::Plugin::TaskWeaver: '0'
  Dist::Zilla::Plugin::Test::Compile: '0'
  Dist::Zilla::Plugin::Test::DistManifest: '0'
  Dist::Zilla::Plugin::Test::MinimumVersion: '0'
  Dist::Zilla::Plugin::Test::Perl::Critic: '0'
  Dist::Zilla::Plugin::Test::PodSpelling: '0'
  Dist::Zilla::Plugin::Test::Portability: '0'
  Dist::Zilla::Plugin::Test::Synopsis: '0'
  Dist::Zilla::Plugin::Test::UnusedVars: '0'
  Dist::Zilla::Plugin::UploadToCPAN: '0'
  Method::Signatures::Simple: '0'
  Moose: '1.00'
  Moose::Util::TypeConstraints: '0'
  MooseX::Types::Email: '0'
  MooseX::Types::Moose: '0'
  MooseX::Types::Structured: '0.20'
  MooseX::Types::URI: '0'
  Pod::Weaver::PluginBundle::MARCEL: '0'
  namespace::autoclean: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-NIGELM
  homepage: https://metacpan.org/release/Dist-Zilla-PluginBundle-NIGELM
  repository: git://github.com/nigelm/dist-zilla-pluginbundle-nigelm.git
version: '0.18'
x_Dist_Zilla:
  perl:
    version: '5.018002'
  plugins:
    -
      class: Dist::Zilla::Plugin::Bootstrap::lib
      config:
        Dist::Zilla::Role::Bootstrap:
          distname: Dist-Zilla-PluginBundle-NIGELM
          fallback: '1'
          try_built: ~
          try_built_method: mtime
      name: Bootstrap::lib
      version: '0.04000002'
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@NIGELM/Git::NextVersion'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@NIGELM/Git::Check'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@NIGELM/GatherDir'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@NIGELM/Test::Compile'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@NIGELM/Test::Perl::Critic'
      version: '2.112410'
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@NIGELM/MetaTests'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@NIGELM/PodCoverageTests'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@NIGELM/PodSyntaxTests'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Test::PodSpelling
      name: '@NIGELM/Test::PodSpelling'
      version: '2.006002'
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@NIGELM/KwaliteeTests'
      version: '1.101420'
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@NIGELM/Test::Portability'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Test::Synopsis
      name: '@NIGELM/Test::Synopsis'
      version: '2.000004'
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@NIGELM/Test::MinimumVersion'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@NIGELM/HasVersionTests'
      version: '1.101420'
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: '@NIGELM/Test::DistManifest'
      version: '2.000004'
    -
      class: Dist::Zilla::Plugin::Test::UnusedVars
      name: '@NIGELM/Test::UnusedVars'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@NIGELM/NoTabsTests'
      version: '0.06'
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@NIGELM/EOLTests'
      version: '0.02'
    -
      class: Dist::Zilla::Plugin::InlineFiles
      name: '@NIGELM/InlineFiles'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::ReportVersions
      name: '@NIGELM/ReportVersions'
      version: '1.110730'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@NIGELM/PruneCruft'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@NIGELM/PruneFiles'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@NIGELM/ManifestSkip'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@NIGELM/AutoPrereqs'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@NIGELM/MetaConfig'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Class
      config:
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
      name: '@NIGELM/MetaProvides::Class'
      version: '1.14000001'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@NIGELM/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '5.012'
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
      name: '@NIGELM/MetaProvides::Package'
      version: '2.000001'
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@NIGELM/MetaResources'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@NIGELM/Authority'
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@NIGELM/ExtraTests'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@NIGELM/NextRelease'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: '@NIGELM/OurPkgVersion'
      version: '0.005001'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          config_plugins:
            - '@MARCEL'
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/prelude'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Name
              name: '@Default/Name'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Version
              name: '@Default/Version'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: FUNCTIONS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@Default/Leftovers'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/postlude'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Installation
              name: '@Default/Installation'
              version: '1.101421'
            -
              class: Pod::Weaver::Section::BugsAndLimitations
              name: '@Default/BugsAndLimitations'
              version: '1.20'
            -
              class: Pod::Weaver::Section::Availability
              name: '@Default/Availability'
              version: '1.20'
            -
              class: Pod::Weaver::Section::Authors
              name: '@Default/Authors'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Legal
              name: '@Default/Legal'
              version: '4.006'
      name: '@NIGELM/PodWeaver'
      version: '4.005'
    -
      class: Dist::Zilla::Plugin::License
      name: '@NIGELM/License'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@NIGELM/ModuleBuild'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@NIGELM/MetaYAML'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@NIGELM/MetaJSON'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@NIGELM/ReadmeTextInBuild'
      version: '0.133360'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@NIGELM/ReadmePodInRoot'
      version: '0.133360'
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@NIGELM/InstallGuide'
      version: '1.200002'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@NIGELM/Manifest'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@NIGELM/Git::Commit'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@NIGELM/Git::Tag'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@NIGELM/Git::CommitBuild'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@NIGELM/Git::Push'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@NIGELM/CheckChangeLog'
      version: '0.01'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@NIGELM/UploadToCPAN'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@NIGELM/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '5.012'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.012'
x_authority: cpan:NIGELM
